"""Mirrored gas budgets and batching constants for the agent layer."""

from decimal import Decimal

SINGLE_TRADE_GAS_TARGET = 180_000
BATCH_TRADE_GAS_TARGET_PER_TRADE = 150_000
SIGNAL_VALIDATION_GAS_BUDGET = 8_000
FLASHLOAN_OVERHEAD_GAS = 25_000
DEX_ROUTING_GAS_PER_LEG = 45_000
PROFIT_SETTLEMENT_GAS = 12_000
MEV_BURN_BASE_GAS = 5_000

BATCH_WINDOW_MS = 5_000
MAX_BATCH_SIZE = 5
MIN_BATCH_FOR_SAVINGS = 2

DEFAULT_ETH_PRICE_USDC = Decimal("2500")
MEV_BURN_THRESHOLD_USDC = Decimal("50.0")
MEV_BURN_PCT = Decimal("2")
