import { SystemMetrics, ActivityEvent, PipelineState, Opportunity, RiskCenter, ExecutionCenter, BroadcastState, OnChainOutcome, SettlementCenter, MarketDataCenter, OracleFeedStatus, ComputeCenter, AdminCenter, Provider, AuditLogEntry, AuditActionType } from '@/types';
interface DashboardStore {
    metrics: SystemMetrics;
    activities: ActivityEvent[];
    loading: boolean;
    lastRefresh: Date | null;
    opportunities: Opportunity[];
    riskCenter: RiskCenter;
    executionCenter: ExecutionCenter;
    marketDataCenter: MarketDataCenter;
    simulateOpportunity: (id: string) => Promise<'valid' | 'marginal' | 'invalid'>;
    approveOpportunity: (id: string) => void;
    rejectOpportunity: (id: string, reason: string) => void;
    getOpportunity: (id: string) => Opportunity | undefined;
    setMetrics: (metrics: SystemMetrics) => void;
    setActivities: (activities: ActivityEvent[]) => void;
    setLoading: (loading: boolean) => void;
    addActivity: (activity: ActivityEvent) => void;
    refreshData: () => Promise<void>;
    acknowledgeBreaker: (breakerId: string) => void;
    acknowledgeOverride: (overrideId: string) => void;
    triggerEmergencyStop: (reason: string, by: string) => Promise<void>;
    clearEmergencyStop: () => void;
    runSimulation: (executionId: string) => Promise<void>;
    broadcastTrade: (executionId: string) => Promise<void>;
    retryExecution: (executionId: string) => Promise<void>;
    updateBroadcastState: (executionId: string, state: BroadcastState) => void;
    updateOnChainOutcome: (executionId: string, outcome: OnChainOutcome) => void;
    getExecution: (executionId: string) => ExecutionCenter;
    simulateMempoolEvents: (count: number) => void;
    settlementCenter: SettlementCenter;
    closePosition: (positionId: string) => void;
    recordRepayment: (repaymentId: string, amount: number) => void;
    generateLedgerExport: (timeRange: {
        start: Date;
        end: Date;
    }) => void;
    compareExpectedVsRealized: (tradeId: string) => void;
    refreshFeeds: () => Promise<void>;
    getFeedByName: (name: 'Pyth' | 'Chainlink' | 'Fallback') => OracleFeedStatus | undefined;
    computeCenter: ComputeCenter;
    verifyPayload: (requestId: string) => Promise<void>;
    replayInference: (requestId: string) => Promise<void>;
    viewTrace: (requestId: string) => void;
    inspectSignature: (requestId: string) => void;
    runDemo: () => void;
    runDemoAuto: () => Promise<void>;
    pipelineDemo: {
        itemId: string;
        computeRequestId: string;
        currentStage: PipelineState | 'discovery' | 'filtering' | 'inference' | 'reasoning' | 'execution' | 'settlement';
        lifecycle: Array<{
            id: string;
            stage: 'discovery' | 'filtering' | 'inference' | 'reasoning' | 'execution' | 'settlement';
            label: string;
            timestamp: Date;
            status: 'queued' | 'processing' | 'complete';
            eventId?: string;
            storageUrl?: string;
        }>;
        playbackIndex: number;
        isPlaying: boolean;
        lastPlaybackAt?: Date;
    };
    startPipelineDemo: () => Promise<void>;
    stepPipelineDemo: () => Promise<void>;
    replayPipelineDemo: () => void;
    setPipelinePlaybackIndex: (index: number) => void;
    adminCenter: AdminCenter;
    editProvider: (providerId: string) => void;
    updateProvider: (providerId: string, config: Partial<Provider>) => Promise<void>;
    updateContract: (contractId: string) => void;
    saveConfig: () => Promise<void>;
    searchAuditLog: (filters: {
        actionType?: AuditActionType;
        subsystem?: string;
        startDate?: Date;
        endDate?: Date;
    }) => AuditLogEntry[];
    filterAuditByType: (actionType: AuditActionType) => AuditLogEntry[];
    downloadReplayReport: () => void;
}
export declare const useDashboardStore: import("zustand").UseBoundStore<import("zustand").StoreApi<DashboardStore>>;
export {};
//# sourceMappingURL=index.d.ts.map